defaults:
  - dataset: grab
  - clip: clip
  - diffusion: diffusion
  - mpnet: mpnet
  - seq_cvae: seq_cvae
  - pointfeat: pointfeat
  - contact: contact
  - texthom: texthom
  - refiner: refiner
project_name: "texthom"
batch_size: 32 # 64, 512
shuffle: True
drop_last: True
num_workers: 4
result_show_freq: 500
save_pth_freq: 2000
text: ["Place cappuccino with right hand."]
save_demo: True
save_obj: True
balance_weights: True
fps: 30

hydra:
  run:
    dir: outputs/${texthom.model_name}/
  # output_subdir: null